title: Kristof Verbraeken
tagline: Full Stack Software Engineer
theme: jekyll-theme-cayman
google_analytics: UA-107833896-1
paginate: 1
url: http://www.braek.be
plugins:
  - jekyll-sitemap
gems:
  - jekyll-paginate