title: Braek
description: Personal website of Kristof Verbraeken
theme: jekyll-theme-cayman
google_analytics: UA-107833896-1
google_site_verification: iD6UF48ujMfrzrCcXRgS5S3O1SH2Aud_wGvTNPbNXac
paginate: 666
url: https://www.koder.be
encoding: UTF-8
lang: en
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
