title: Braek
description: Personal website of Kristof Verbraeken
theme: jekyll-theme-time-machine
google_analytics: UA-107833896-1
paginate: 666
url: http://www.braek.be
encoding: UTF-8
lang: en
plugins:
  - jekyll-sitemap
